name: CI
on: [push]
jobs:
  test:
    strategy:
      matrix:
        runs-on: ["macOS-latest", "ubuntu-latest"]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v1

      - name: Install tools
        run: |
          brew install --build-bottle --verbose Formula/kdash.rb && kdash -h
